### ISSUE TITLE
Similar plugins on plugin page missing entries

### ISSUE THREAD

**Issue by selfthinker** [dokuwiki/dokuwiki-plugin-pluginrepo#102]
When a plugin marks another plugin as similar, the other plugin page would show it as similar as well without the need to add it to the page. But that functionality seems to be broken.

E.g. [plugin:wrap](https://www.dokuwiki.org/plugin:wrap) has "pagebreak" as one of the similar plugins, but [plugin:pagebreak](https://www.dokuwiki.org/plugin:pagebreak) doesn't have "wrap" listed.

On the other hand the Wrap plugin lists several similar plugins which it doesn't list in its markup, so it generally still seems to work.

**Comment by Klap-in** [comment]
Seems to be solved, I cannot come up with other deviations.
