### ISSUE TITLE
via api.php extensions with strange types are also listed

### ISSUE THREAD

**Issue by Klap-in** [dokuwiki/dokuwiki-plugin-pluginrepo#117]
Type should be 'plugin' or 'template'. 
Probably these wrong types originate from namespace of repository entries that are stored at wrong location.

See also:
https://github.com/splitbrain/dokuwiki-extensionmirror/commit/12aba0c584bf023781222c9d3d5a81c38d6639a1

Maybe idea to disable or give warning for repository entries outside the 'plugin' and 'template' namespace. Such that wiki editors can fix them self already.

**Comment by splitbrain** [comment]
Related: splitbrain/dokuwiki#2370

**Comment by Klap-in** [comment]
The extension mirror script checks the stored ids. Which contain just the namespace.

#119 does save only plugin and template pages that are directly in `plugin:` or `template:`. Also translations are not saved.
If outside plugin: or template: then also a warning is shown.

If some from 'types' are still there, these has to be removed by resaving.
