### ISSUE TITLE
add field updatemessage

### ISSUE THREAD

**Issue by Klap-in** [dokuwiki/dokuwiki-plugin-pluginrepo#144]
Are there opinions about adding a field mentioned 'updatemessage' which plugin authors can use to share an note regarding the offered update? Now the 'securitywarning' is sometimes used for this purpose.

Idea is to show it as 'Update message: ....<written text>... '. In same yellow layout at the other messages.
This needs change of the Extension Manager as well.

**Comment by splitbrain** [comment]
Yeah, might be a good idea.
