### ISSUE TITLE
Field data is saved with leading whitespace

### ISSUE THREAD

**Issue by splitbrain** [dokuwiki/dokuwiki-plugin-pluginrepo#151]
Today https://github.com/cosmocode/dokuwiki-plugin-imgpaste/issues/33 was reported.

The issue was caused by the plugin page having been deleted, then later being readded. This means all data for the plugin has been resaved.

Looking at the API result for the plugins shows that all data has been saved with leading whitespace:

https://www.dokuwiki.org/lib/plugins/pluginrepo/api.php?ext[]=imgpaste

I believe the issue was introduced in 2d443e462bcef11768413cdb9e032a0957e38ca9 leading to this code: 

https://github.com/dokuwiki/dokuwiki-plugin-pluginrepo/blob/a9d9879c7651ac4918aba9a867236a14cfe2b75f/helper/repository.php#L78-L82

To me this looks like every field that has no previous value gets prefixed with a whitespace.

I am wondering what this code was meant to do?

**Comment by Klap-in** [comment]
It should concatenate values that are added with help of multiple lines, I guess I swapped actions. Before it concatenates when `if ($data[$key]) { `.
