### ISSUE TITLE
Compatible "yyyy-mm-dd+" not fully working

### ISSUE THREAD

**Issue by selfthinker** [dokuwiki/dokuwiki-plugin-pluginrepo#71]
The "yyyy-mm-dd+" syntax used in the "compatible" field doesn't seem to be working anymore. See e.g. https://www.dokuwiki.org/plugin:sync. That also means that those plugins will only show at the very bottom of the plugin list under "Compatible with older DokuWiki versions" although many of them will be compatible with the latest version.

I personally never liked that syntax, but as long as we support it, this should be fixed. Or we should stop supporting it.

**Comment by Klap-in** [comment]
So dropping interpretation of compatibility version after the most recent 4 version is by design.

The consequence is that for old, not changed, plugins with a  "yyyy-mm-dd+" syntax the compatibility field has to be updated every 4 versions ( ~ 2 years ).

**Comment by Klap-in** [comment]
What is the current value of 'plugin»pluginrepo»releases' in the Config Manager?

**Comment by selfthinker** [comment]
> What is the current value of 'plugin»pluginrepo»releases' in the Config Manager?

It's
```
2014-09-29 "Hrun",2014-05-05 "Ponder Stibbons", 2013-12-08 "Binky", 2013-05-10 "Weatherwax", 2012-10-13 "Adora Belle", 2012-01-25 "Angua", 2011-05-25 "Rincewind"
```

**Comment by Klap-in** [comment]
Then the + syntax is working for releases of 2011-05-25 and newer. Not for older ones. I think that is fine.

For older plugins it is fine that it requires some manual updating of the compatibility field imho.

**Comment by Klap-in** [comment]
e.g. at the moment we have the versions until 2014, which long enough to work the + a reasonable time. Its behaviour depends thus a bit on what is in the config field.
